-- Finance tables are included in backend/supabase/schema.sql
-- Run schema.sql directly in Supabase SQL Editor.
-- Tables included: transactions, budgets, debts, savings_goals
-- All with RLS policies tied to auth.uid() = user_id
